"use client";

// Единый набор векторных иконок (lucide) вместо разношёрстных эмодзи.
// Иконка задаётся именем в data/exercises.js, цвет наследует от родителя.
import {
  Activity,
  AlarmClock,
  CloudFog,
  CloudLightning,
  CloudRain,
  Citrus,
  Coffee,
  DoorClosed,
  Dumbbell,
  Ear,
  Eye,
  Flame,
  Footprints,
  GlassWater,
  Hand,
  Heart,
  HeartHandshake,
  Hourglass,
  Laugh,
  MessageCircle,
  Mic,
  Moon,
  Phone,
  RotateCw,
  ScanFace,
  ShieldCheck,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  TreePine,
  Utensils,
  Waves,
  Wind,
} from "lucide-react";

const MAP = {
  Activity,
  AlarmClock,
  CloudFog,
  CloudLightning,
  CloudRain,
  Citrus,
  Coffee,
  DoorClosed,
  Dumbbell,
  Ear,
  Eye,
  Flame,
  Footprints,
  GlassWater,
  Hand,
  Heart,
  HeartHandshake,
  Hourglass,
  Laugh,
  MessageCircle,
  Mic,
  Moon,
  Phone,
  RotateCw,
  ScanFace,
  ShieldCheck,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  TreePine,
  Utensils,
  Waves,
  Wind,
};

export default function ExIcon({ name, size = 22, strokeWidth = 2, style, color }) {
  const C = MAP[name];
  if (!C) return null;
  return <C size={size} strokeWidth={strokeWidth} style={style} color={color} aria-hidden="true" />;
}
